import numpy as np
import pytest
import torch

from hydrophysics.twin.calibrate_mlcw import fit_column, loso
from hydrophysics.twin.compaction import VEPColumn


def test_elastic_compaction_is_fully_recoverable():
    """Pure elastic loading then unloading must return to zero compaction."""
    col = VEPColumn(n_sites=1)
    with torch.no_grad():
        col.log_ske.fill_(torch.log(torch.tensor(1e-3)).item())
        col.log_skv.fill_(-30.0)     # inelastic off
        col.log_tau.fill_(-10.0)     # instantaneous
        col.h_pc0.fill_(-1e3)        # preconsolidation far below -> never gated on
    h = torch.tensor([[0.0, -5.0, -10.0, -5.0, 0.0]])
    s = col(h)
    assert s[0, 0].item() == pytest.approx(0.0, abs=1e-9)
    assert s[0, 2].item() > 0.0                       # head fell -> subsidence
    assert s[0, 4].item() == pytest.approx(0.0, abs=1e-6)   # head recovered -> recovered


def test_elastic_magnitude_follows_ske():
    col = VEPColumn(n_sites=2)
    with torch.no_grad():
        col.log_ske[0] = torch.log(torch.tensor(1e-3))
        col.log_ske[1] = torch.log(torch.tensor(2e-3))
        col.log_skv.fill_(-30.0)
        col.log_tau.fill_(-10.0)
        col.h_pc0.fill_(-1e3)
    h = torch.tensor([[0.0, -10.0], [0.0, -10.0]])
    s = col(h)
    assert s[1, 1].item() == pytest.approx(2.0 * s[0, 1].item(), rel=1e-5)


def test_gradients_flow_to_parameters():
    col = VEPColumn(n_sites=1)
    h = torch.tensor([[0.0, -3.0, -6.0]])
    col(h).sum().backward()
    assert col.log_ske.grad is not None
    assert torch.isfinite(col.log_ske.grad).all()


def test_inelastic_strain_is_never_recovered():
    """Below the preconsolidation head, compaction is permanent."""
    col = VEPColumn(n_sites=1)
    with torch.no_grad():
        col.log_ske.fill_(torch.log(torch.tensor(1e-4)).item())
        col.log_skv.fill_(torch.log(torch.tensor(1e-2)).item())
        col.log_tau.fill_(-10.0)      # instantaneous: isolate the gate
        col.h_pc0.fill_(0.0)          # preconsolidated at h = 0
    h = torch.tensor([[0.0, -10.0, 0.0]])
    s = col(h)
    assert s[0, 1].item() > 0.0
    assert s[0, 2].item() > 0.5 * s[0, 1].item()   # most of it stays after recovery


def test_no_inelastic_above_preconsolidation_head():
    col = VEPColumn(n_sites=1)
    with torch.no_grad():
        col.log_ske.fill_(torch.log(torch.tensor(1e-4)).item())
        col.log_skv.fill_(torch.log(torch.tensor(1e-2)).item())
        col.log_tau.fill_(-10.0)
        col.h_pc0.fill_(-20.0)        # already preconsolidated well below the loading
    h = torch.tensor([[0.0, -10.0, 0.0]])
    s = col(h)
    assert s[0, 2].item() == pytest.approx(0.0, abs=1e-6)   # purely elastic, recovers


def _step_response(tau_days, n_steps=60, dt=30.0):
    col = VEPColumn(n_sites=1, dt_days=dt)
    with torch.no_grad():
        col.log_ske.fill_(-30.0)                                  # elastic off
        col.log_skv.fill_(torch.log(torch.tensor(1e-2)).item())
        col.log_tau.fill_(torch.log(torch.tensor(float(tau_days))).item())
        col.h_pc0.fill_(0.0)
    h = torch.cat([torch.zeros(1, 1), torch.full((1, n_steps - 1), -10.0)], dim=1)
    return col(h)[0]


def test_tau_small_reproduces_the_instantaneous_limit():
    fast = _step_response(1e-3)
    assert fast[1].item() == pytest.approx(fast[-1].item(), rel=1e-3)   # arrives at once


def test_tau_large_suppresses_compaction_within_the_window():
    slow = _step_response(1e6)
    fast = _step_response(1e-3)
    assert slow[-1].item() < 0.05 * fast[-1].item()


def test_intermediate_tau_relaxes_monotonically_toward_equilibrium():
    mid = _step_response(365.0)
    d = torch.diff(mid[1:])
    assert torch.all(d >= -1e-9)                    # monotone approach
    assert mid[-1].item() > mid[2].item()           # still rising: memory present


def _synthetic(n_sites=6, T=80, seed=0):
    """Heads and compaction generated BY the model, so recovery is checkable."""
    g = torch.Generator().manual_seed(seed)
    t = torch.arange(T, dtype=torch.float32)
    h = -(t / T) * (5.0 + 10.0 * torch.rand(n_sites, 1, generator=g))
    h = h + 0.5 * torch.sin(2 * torch.pi * t / 12.0)
    truth = VEPColumn(n_sites=n_sites)
    with torch.no_grad():
        truth.log_ske.copy_(torch.log(torch.full((n_sites,), 5e-4)))
        truth.log_skv.copy_(torch.log(torch.full((n_sites,), 8e-3)))
        truth.log_tau.copy_(torch.log(torch.full((n_sites,), 200.0)))
        truth.h_pc0.zero_()
    obs = truth(h).detach()
    return h, obs, torch.ones_like(obs, dtype=torch.bool)


def test_fit_column_recovers_synthetic_compaction():
    h, obs, mask = _synthetic()
    model, info = fit_column(h, obs, mask, epochs=800, lr=0.05)
    dev = next(model.parameters()).device          # fit_column may have moved to CUDA
    pred = model(h.to(dev)).detach().cpu()
    ss_res = ((pred - obs) ** 2).sum().item()
    ss_tot = ((obs - obs.mean()) ** 2).sum().item()
    assert 1.0 - ss_res / ss_tot > 0.95
    assert info["loss"] < 1e-4


def test_loso_returns_a_finite_gate_number():
    h, obs, mask = _synthetic()
    out = loso(h, obs, mask, epochs=800, lr=0.05)
    assert np.isfinite(out["r2"])
    assert out["n_sites"] == h.shape[0]
    # All six synthetic sites share identical true parameters, so a correct cross-site
    # transfer must score well -- this is not just a finiteness check.
    assert out["r2"] > 0.95


def test_inelastic_gate_opens_for_all_positive_heads():
    """A site whose heads never cross the datum must still accrue permanent strain.

    Regression: `h_pc` was once `min(h_pc0, h[:, 0])` with `h_pc0` init 0.0, so at any site
    whose heads stayed above 0 m the gate never opened and `log_skv`/`log_tau` received no
    gradient. That silently disabled the inelastic term at 7 of the 14 Choushui MLCW sites.
    `h_pc0` is now an offset from `h[:, 0]`, so the gate is datum-independent.
    """
    col = VEPColumn(n_sites=1)
    with torch.no_grad():
        col.log_ske.fill_(torch.log(torch.tensor(1e-4)).item())
        col.log_skv.fill_(torch.log(torch.tensor(1e-2)).item())
        col.log_tau.fill_(-10.0)      # instantaneous: isolate the gate
        col.h_pc0.zero_()             # normally consolidated at t=0
    # heads far above the datum, drawn down then recovered
    h = torch.tensor([[25.0, 15.0, 25.0]])
    s = col(h)
    assert s[0, 1].item() > 0.0
    assert s[0, 2].item() > 0.5 * s[0, 1].item()      # permanent strain remains

    # and the inelastic parameters must actually receive gradient
    col.zero_grad()
    col(h).sum().backward()
    assert col.log_skv.grad is not None and col.log_skv.grad.abs().item() > 0.0
