"""Shared demo-data builder for the HydroPhysicsAI Gradio Space.

Builds a 61-well *synthetic* dataset whose static metadata (coordinates, station
names, coastal/inland group, distance-to-coast) are the REAL Zhuoshui monitoring
network values read from ``app/stations.csv`` -- but whose target / rainfall /
upstream TIME SERIES are entirely SYNTHETIC (generated by
:func:`hydrophysics.sample.write_sample`).

Data policy: only LOCATION/BOUNDARY metadata (coordinates, names, group, GIS
outlines) is real and publishable. No real groundwater or rainfall series ever
touch this module -- the plotted series are illustrative fabrications.

Two entry points:
  * :func:`build_synthetic_data` -- returns a :class:`GWData` with real attrs.
  * the ``__main__`` block -- precomputes predictions on (optionally) CUDA and
    writes a compact ``app/artifact.npz`` the Space loads instantly at startup.
"""

from __future__ import annotations

import tempfile
from pathlib import Path

import numpy as np
import pandas as pd

from hydrophysics.config import Config
from hydrophysics.data import GWData, load_dataset
from hydrophysics.sample import write_sample

APP_DIR = Path(__file__).resolve().parent
STATIONS_CSV = APP_DIR / "stations.csv"
ARTIFACT = APP_DIR / "artifact.npz"
ET_DEMO = APP_DIR / "et_demo.npz"
OPERATOR_PT = APP_DIR / "models" / "operator.pt"

# Synthetic record span (kept identical to what the precompute used so the cached
# arrays line up with a freshly built fallback dataset).
START, END, SEED = "2014-01-01", "2019-12-31", 7


def load_stations() -> pd.DataFrame:
    """Real station metadata (coords/name/group/dist), indexed by st_id."""
    df = pd.read_csv(STATIONS_CSV, dtype={"st_id": str})
    return df.set_index("st_id")


def build_synthetic_data() -> GWData:
    """61-well GWData: SYNTHETIC series, REAL location/name/group attrs.

    The synthetic generator mirrors the real signal structure (seasonal recession +
    rainfall response + upstream coupling) so the exact model code paths run; only
    the static per-well attributes are swapped for the real network metadata.
    """
    stations = load_stations()
    n = len(stations)

    tmp = tempfile.mkdtemp(prefix="hydro_demo_")
    d = write_sample(tmp, n_wells=n, seed=SEED, start=START, end=END)
    data = load_dataset(Config(data_dir=d))

    # Overwrite the synthetic placeholder attrs with the REAL network metadata.
    # well_ids are st1..st61 in order, matching stations.csv st_id order.
    ids = list(data.well_ids)
    s = stations.reindex(ids)
    a = data.attrs
    a["name"] = s["name"].to_numpy()
    a["tm_x"] = s["tm_x"].to_numpy(dtype=float)
    a["tm_y"] = s["tm_y"].to_numpy(dtype=float)
    a["group"] = s["group"].to_numpy()
    a["is_coastal"] = (s["group"].to_numpy() == "coastal").astype(int)
    a["dist_to_coast_m"] = s["dist_to_coast_m"].to_numpy(dtype=float)
    return data


def _train_and_predict(data: GWData, device: str, ude_epochs: int, fc_epochs: int):
    """Train the BEST recharge-memory operator on NET recharge (rain - ET0) plus the
    probabilistic forecaster, and return everything the demo ships.

    Returns ``(ude, sim, mean_cube, sigma_cube, et0, net_data)`` where ``ude`` is the
    trained PhysicsUDE operator (fit on net recharge), ``sim`` its baseline simulation,
    ``et0`` the (W, T) demo-period ET0, and ``net_data`` the GWData whose ``rainfall``
    field is the net recharge the operator consumes (rain - ET0).
    """
    from hydrophysics.et import et0_for_data, net_recharge
    from hydrophysics.models.forecast_lstm import GlobalForecastLSTM
    from hydrophysics.models.ude import PhysicsUDE

    # ET0 for the demo period (Open-Meteo ERA5; cached to app/et_demo.npz).
    et0 = et0_for_data(data, cache_path=str(ET_DEMO))
    # Net recharge = synthetic rainfall - ET0: the forcing the BEST operator consumes.
    net_data = net_recharge(data, et0=et0)

    # BEST operator: recharge-memory hypernetwork, fit on net recharge.
    ude = PhysicsUDE(rain_memory=(0.99, 0.95, 0.85), device=device,
                     epochs=ude_epochs, seed=0).fit(net_data)
    sim = ude.simulate(net_data)

    # Forecaster keeps consuming the raw synthetic series (unchanged).
    fc = GlobalForecastLSTM(lookback=90, horizon=30, hidden=64, epochs=fc_epochs,
                            probabilistic=True, device=device, seed=0).fit(data)
    mean_cube, sigma_cube = fc.forecast_dist(data)
    return ude, sim, mean_cube, sigma_cube, et0, net_data


def save_artifact(data: GWData, sim, mean, sigma, et0, path: Path = ARTIFACT) -> Path:
    """Persist ONLY synthetic series + predictions (no real series anywhere).

    The forecast panel only ever reads origins inside the validation window, so the
    (W, T, H) mean/sigma cubes are stored sliced to those origins (``fc_t0``) to keep
    the artifact a few MB.

    The what-if panel re-simulates live, so the forcing is now shipped too: the SYNTHETIC
    rainfall (W, T) and the demo-period ET0 (W, T, real public ERA5). At load time the
    operator's input field (net recharge = rain - ET0) is reconstructed from them. The
    groundwater/rainfall TIME SERIES remain synthetic; only ET0 is real.
    """
    H = mean.shape[2]
    val_idx = np.where(data.val_mask)[0]
    v0, v1 = int(val_idx[0]), int(val_idx[-1])
    # Valid forecast origins: inside the validation window with a full horizon ahead.
    fc_t0 = np.arange(v0, min(v1 - H, data.n_days - H - 1) + 1, dtype=np.int32)

    # The operator conditions its hypernetwork on _static_features(attrs); some of those
    # columns (dom_amp, ups_lag_days, rf_lag_days) come from the synthetic sample writer
    # and are NOT reconstructable from stations.csv. Ship the exact static-feature matrix
    # so the loaded operator sees the identical conditioning it was trained on (otherwise
    # the standardized features shift and the hypernetwork emits garbage parameters).
    from hydrophysics.models.gru import _static_features
    static_feats = _static_features(data).astype(np.float32)

    np.savez_compressed(
        path,
        well_ids=np.array(list(data.well_ids)),
        dates=np.array([d.isoformat() for d in data.dates]),
        target=data.target.astype(np.float32),     # SYNTHETIC level series
        rainfall=np.nan_to_num(data.rainfall).astype(np.float32),  # SYNTHETIC rainfall
        et0=np.nan_to_num(et0).astype(np.float32),  # REAL public ERA5 ET0 (mm/day)
        static_feats=static_feats,                  # operator conditioning (W, F_static)
        train_mask=data.train_mask,
        val_mask=data.val_mask,
        sim=sim.astype(np.float32),                 # SYNTHETIC simulation hindcast
        fc_t0=fc_t0,                                # forecast-origin day indices
        fc_mean=mean[:, fc_t0, :].astype(np.float32),
        fc_sigma=sigma[:, fc_t0, :].astype(np.float32),
        split_date=np.array(data.split_date),
    )
    return path


def load_artifact(path: Path = ARTIFACT):
    """Reconstruct (GWData, sim, mean, sigma, rainfall, et0) from the shipped artifact.

    The mean/sigma cubes are re-expanded to full (W, T, H) shape (NaN outside stored
    validation origins) so the app code can index ``MEAN[i, t0]`` unchanged.

    ``data.rainfall`` is set to the BASELINE net recharge (synthetic rain - real ET0) so
    the trained operator simulates correctly straight from the loaded data; the raw
    synthetic ``rainfall`` and real ``et0`` arrays are returned alongside so the what-if
    panel can re-mix ``net = rain*rain_mult - et0*et_mult`` and re-simulate live.
    Older artifacts without these fields fall back to NaN rainfall (no what-if).
    """
    z = np.load(path, allow_pickle=False)
    well_ids = [str(w) for w in z["well_ids"]]
    dates = pd.DatetimeIndex(pd.to_datetime([d for d in z["dates"]]))
    stations = load_stations().reindex(well_ids)

    attrs = pd.DataFrame(index=pd.Index(well_ids, name="st_id"))
    attrs["name"] = stations["name"].to_numpy()
    attrs["group"] = stations["group"].to_numpy()
    attrs["tm_x"] = stations["tm_x"].to_numpy(dtype=float)
    attrs["tm_y"] = stations["tm_y"].to_numpy(dtype=float)
    attrs["dist_to_coast_m"] = stations["dist_to_coast_m"].to_numpy(dtype=float)
    attrs["is_coastal"] = (stations["group"].to_numpy() == "coastal").astype(int)

    # Restore the EXACT operator-conditioning columns from the shipped static-feature
    # matrix (in _static_features' fixed column order). Without this the synthetic-only
    # columns (dom_amp, ups_lag_days, rf_lag_days) would be zero at load and the loaded
    # operator's hypernetwork would emit garbage parameters.
    if "static_feats" in z.files:
        sf = z["static_feats"].astype(float)
        for j, col in enumerate(
                ["tm_x", "tm_y", "is_coastal", "dist_to_coast_m",
                 "dom_amp", "ups_lag_days", "rf_lag_days"]):
            attrs[col] = sf[:, j]

    target = z["target"].astype(float)
    W, T = target.shape
    H = z["fc_mean"].shape[2]
    mean = np.full((W, T, H), np.nan)
    sigma = np.full((W, T, H), np.nan)
    fc_t0 = z["fc_t0"]
    mean[:, fc_t0, :] = z["fc_mean"].astype(float)
    sigma[:, fc_t0, :] = z["fc_sigma"].astype(float)

    # Forcing: synthetic rainfall + real ET0. The operator consumes net recharge.
    if "rainfall" in z.files and "et0" in z.files:
        rainfall = z["rainfall"].astype(float)
        et0 = z["et0"].astype(float)
        net = (rainfall - et0).astype(float)   # baseline net recharge (operator input)
    else:
        rainfall = np.full_like(target, np.nan)
        et0 = np.full_like(target, np.nan)
        net = np.full_like(target, np.nan)

    data = GWData(
        well_ids=well_ids,
        dates=dates,
        target=target,
        rainfall=net,
        upstream=np.full_like(target, np.nan),
        doy=dates.dayofyear.to_numpy().astype(int),
        train_mask=z["train_mask"],
        val_mask=z["val_mask"],
        attrs=attrs,
        split_date=str(z["split_date"]),
    )
    return data, z["sim"].astype(float), mean, sigma, rainfall, et0


if __name__ == "__main__":
    import argparse
    import time

    import torch

    p = argparse.ArgumentParser(description="Precompute the demo artifact.")
    p.add_argument("--device", default="cuda" if torch.cuda.is_available() else "cpu")
    p.add_argument("--ude-epochs", type=int, default=600)
    p.add_argument("--fc-epochs", type=int, default=80)
    args = p.parse_args()

    t0 = time.time()
    data = build_synthetic_data()
    print(f"built synthetic 61-well data in {time.time() - t0:.1f}s; {data.summary()}")
    t1 = time.time()
    ude, sim, mean, sigma, et0, net_data = _train_and_predict(
        data, args.device, args.ude_epochs, args.fc_epochs)
    print(f"trained + predicted on {args.device} in {time.time() - t1:.1f}s")

    # Ship the trained operator CPU-loadable. Move the small hypernetwork to CPU so
    # torch.load(map_location='cpu') works on a CPU-only Space.
    import torch
    ude.device = "cpu"
    ude.hypernet = ude.hypernet.to("cpu")
    OPERATOR_PT.parent.mkdir(parents=True, exist_ok=True)
    torch.save(ude, OPERATOR_PT)
    op_mb = OPERATOR_PT.stat().st_size / 1e6
    print(f"wrote {OPERATOR_PT} ({op_mb:.3f} MB)")

    out = save_artifact(data, sim, mean, sigma, et0)
    mb = out.stat().st_size / 1e6
    print(f"wrote {out} ({mb:.2f} MB)")
    if ET_DEMO.exists():
        print(f"ET0 cache {ET_DEMO} ({ET_DEMO.stat().st_size / 1e6:.2f} MB)")
