"""Shared demo-data builder for the HydroPhysicsAI Gradio Space.

Builds a 61-well *synthetic* dataset whose static metadata (coordinates, station
names, coastal/inland group, distance-to-coast) are the REAL Zhuoshui monitoring
network values read from ``app/stations.csv`` -- but whose target / rainfall /
upstream TIME SERIES are entirely SYNTHETIC (generated by
:func:`hydrophysics.sample.write_sample`).

Data policy: only LOCATION/BOUNDARY metadata (coordinates, names, group, GIS
outlines) is real and publishable. No real groundwater or rainfall series ever
touch this module -- the plotted series are illustrative fabrications.

Two entry points:
  * :func:`build_synthetic_data` -- returns a :class:`GWData` with real attrs.
  * the ``__main__`` block -- precomputes predictions on (optionally) CUDA and
    writes a compact ``app/artifact.npz`` the Space loads instantly at startup.
"""

from __future__ import annotations

import tempfile
from pathlib import Path

import numpy as np
import pandas as pd

from hydrophysics.config import Config
from hydrophysics.data import GWData, load_dataset
from hydrophysics.sample import write_sample

APP_DIR = Path(__file__).resolve().parent
STATIONS_CSV = APP_DIR / "stations.csv"
ARTIFACT = APP_DIR / "artifact.npz"

# Synthetic record span (kept identical to what the precompute used so the cached
# arrays line up with a freshly built fallback dataset).
START, END, SEED = "2014-01-01", "2019-12-31", 7


def load_stations() -> pd.DataFrame:
    """Real station metadata (coords/name/group/dist), indexed by st_id."""
    df = pd.read_csv(STATIONS_CSV, dtype={"st_id": str})
    return df.set_index("st_id")


def build_synthetic_data() -> GWData:
    """61-well GWData: SYNTHETIC series, REAL location/name/group attrs.

    The synthetic generator mirrors the real signal structure (seasonal recession +
    rainfall response + upstream coupling) so the exact model code paths run; only
    the static per-well attributes are swapped for the real network metadata.
    """
    stations = load_stations()
    n = len(stations)

    tmp = tempfile.mkdtemp(prefix="hydro_demo_")
    d = write_sample(tmp, n_wells=n, seed=SEED, start=START, end=END)
    data = load_dataset(Config(data_dir=d))

    # Overwrite the synthetic placeholder attrs with the REAL network metadata.
    # well_ids are st1..st61 in order, matching stations.csv st_id order.
    ids = list(data.well_ids)
    s = stations.reindex(ids)
    a = data.attrs
    a["name"] = s["name"].to_numpy()
    a["tm_x"] = s["tm_x"].to_numpy(dtype=float)
    a["tm_y"] = s["tm_y"].to_numpy(dtype=float)
    a["group"] = s["group"].to_numpy()
    a["is_coastal"] = (s["group"].to_numpy() == "coastal").astype(int)
    a["dist_to_coast_m"] = s["dist_to_coast_m"].to_numpy(dtype=float)
    return data


def _train_and_predict(data: GWData, device: str, ude_epochs: int, fc_epochs: int):
    from hydrophysics.models.forecast_lstm import GlobalForecastLSTM
    from hydrophysics.models.ude import PhysicsUDE

    ude = PhysicsUDE(device=device, epochs=ude_epochs, seed=0).fit(data)
    sim = ude.simulate(data)

    fc = GlobalForecastLSTM(lookback=90, horizon=30, hidden=64, epochs=fc_epochs,
                            probabilistic=True, device=device, seed=0).fit(data)
    mean_cube, sigma_cube = fc.forecast_dist(data)
    return sim, mean_cube, sigma_cube


def save_artifact(data: GWData, sim, mean, sigma, path: Path = ARTIFACT) -> Path:
    """Persist ONLY synthetic series + predictions (no real series anywhere).

    The forecast panel only ever reads origins inside the validation window, so the
    (W, T, H) mean/sigma cubes are stored sliced to those origins (``fc_t0``) to keep
    the artifact a few MB. Rainfall is not plotted and is intentionally omitted.
    """
    H = mean.shape[2]
    val_idx = np.where(data.val_mask)[0]
    v0, v1 = int(val_idx[0]), int(val_idx[-1])
    # Valid forecast origins: inside the validation window with a full horizon ahead.
    fc_t0 = np.arange(v0, min(v1 - H, data.n_days - H - 1) + 1, dtype=np.int32)

    np.savez_compressed(
        path,
        well_ids=np.array(list(data.well_ids)),
        dates=np.array([d.isoformat() for d in data.dates]),
        target=data.target.astype(np.float32),     # SYNTHETIC level series
        train_mask=data.train_mask,
        val_mask=data.val_mask,
        sim=sim.astype(np.float32),                 # SYNTHETIC simulation hindcast
        fc_t0=fc_t0,                                # forecast-origin day indices
        fc_mean=mean[:, fc_t0, :].astype(np.float32),
        fc_sigma=sigma[:, fc_t0, :].astype(np.float32),
        split_date=np.array(data.split_date),
    )
    return path


def load_artifact(path: Path = ARTIFACT):
    """Reconstruct (GWData, sim, mean, sigma) from the shipped synthetic artifact.

    The mean/sigma cubes are re-expanded to full (W, T, H) shape (NaN outside stored
    validation origins) so the app code can index ``MEAN[i, t0]`` unchanged.
    """
    z = np.load(path, allow_pickle=False)
    well_ids = [str(w) for w in z["well_ids"]]
    dates = pd.DatetimeIndex(pd.to_datetime([d for d in z["dates"]]))
    stations = load_stations().reindex(well_ids)

    attrs = pd.DataFrame(index=pd.Index(well_ids, name="st_id"))
    attrs["name"] = stations["name"].to_numpy()
    attrs["group"] = stations["group"].to_numpy()
    attrs["tm_x"] = stations["tm_x"].to_numpy(dtype=float)
    attrs["tm_y"] = stations["tm_y"].to_numpy(dtype=float)
    attrs["dist_to_coast_m"] = stations["dist_to_coast_m"].to_numpy(dtype=float)
    attrs["is_coastal"] = (stations["group"].to_numpy() == "coastal").astype(int)

    target = z["target"].astype(float)
    W, T = target.shape
    H = z["fc_mean"].shape[2]
    mean = np.full((W, T, H), np.nan)
    sigma = np.full((W, T, H), np.nan)
    fc_t0 = z["fc_t0"]
    mean[:, fc_t0, :] = z["fc_mean"].astype(float)
    sigma[:, fc_t0, :] = z["fc_sigma"].astype(float)

    data = GWData(
        well_ids=well_ids,
        dates=dates,
        target=target,
        rainfall=np.full_like(target, np.nan),
        upstream=np.full_like(target, np.nan),
        doy=dates.dayofyear.to_numpy().astype(int),
        train_mask=z["train_mask"],
        val_mask=z["val_mask"],
        attrs=attrs,
        split_date=str(z["split_date"]),
    )
    return data, z["sim"].astype(float), mean, sigma


if __name__ == "__main__":
    import argparse
    import time

    import torch

    p = argparse.ArgumentParser(description="Precompute the demo artifact.")
    p.add_argument("--device", default="cuda" if torch.cuda.is_available() else "cpu")
    p.add_argument("--ude-epochs", type=int, default=600)
    p.add_argument("--fc-epochs", type=int, default=80)
    args = p.parse_args()

    t0 = time.time()
    data = build_synthetic_data()
    print(f"built synthetic 61-well data in {time.time() - t0:.1f}s; {data.summary()}")
    t1 = time.time()
    sim, mean, sigma = _train_and_predict(data, args.device, args.ude_epochs, args.fc_epochs)
    print(f"trained + predicted on {args.device} in {time.time() - t1:.1f}s")
    out = save_artifact(data, sim, mean, sigma)
    mb = out.stat().st_size / 1e6
    print(f"wrote {out} ({mb:.2f} MB)")
